// Generated by Haxe 4.0.0-preview.5+6d16e1c47
(function () { "use strict";
var $hxEnums = $hxEnums || {};
var LocaleKeys = function() { };
LocaleKeys.translate = function(key) {
	return key.toUpperCase();
};
LocaleKeys.display = function(text) {
	console.log("src/localeKeys/LocaleKeys.hx:16:",text);
};
LocaleKeys.main = function() {
	var translatedMessage = LocaleKeys.translate("hello");
	LocaleKeys.display(translatedMessage);
};
LocaleKeys.main();
})();
